### ISSUE TITLE
cURL

### ISSUE THREAD

**Issue by filfat** [devkitPro/3ds_portlibs#1]
Adding support for cURL would make my life quite a lot easier.

Thanks! :smiley:

**Comment by kitling** [comment]
Indeed. Not everyone has wget installed by default.

**Comment by mtheall** [comment]
Does curl not work with https://github.com/devkitPro/3ds_portlibs/blob/5751bcdb/Makefile#L79

**Comment by kitling** [comment]
Why hello there! I'd say it probably does, but I'm not benefiting from it due to using outdated forks. I only commented becuase this issue was open, which led me to believe it hadn't been fixed upstream. Should probably close it. ._.

**Comment by filfat** [comment]
No... No.. No.. I meant the library cURL...

**Comment by mtheall** [comment]
Oh you should have been more specific.

**Comment by kitling** [comment]
Lol. xD Sorry.

You could make a PR with cURL support added in, otherwise, once I'm finished pulling stuff in from forks, I can take a look at doing cURL. (Given that it probably needs to interact with the 3ds services to actually port it, I doubt I'll end up doing it.)

**Comment by filfat** [comment]
@mtheall Yep, error on my front 😅

**Comment by Steveice10** [comment]
This issue is pretty old, but I've just submitted a PR to add curl: https://github.com/devkitPro/3ds_portlibs/pull/34

**Comment by WinterMute** [comment]
added with https://github.com/devkitPro/3ds_portlibs/pull/36
