### ISSUE TITLE
Compiling With MinGW Results In "cannot find native C compiler"

### ISSUE THREAD

**Issue by saphtea** [devkitPro/3ds_portlibs#10]
Hey! So I've been able to compile sf2dlib, sfillib, libpng portlib, and libjpeg-turbo just fine, but when I come to compile sftdlib it gives me the error "configure: error: cannot find native C compiler". I am using MinGW so I imagine that could be apart of the issue, but it seems like I should still be able to compile and it may be an issue with the makefile. Thanks for reading this!

Also, here's an image of the error and some of the lines surrounding it.
![image](https://cloud.githubusercontent.com/assets/272940/19374832/a64854ce-9183-11e6-829e-c370e3d477ee.png)

**Comment by DevDivega** [comment]
Check to make sure /path/to/MinGW/bin is in your path and that you have the base system installed. I had the same problem, it occurs because freetype needs gcc in order to compile.

**Comment by WinterMute** [comment]
This is unrelated to portlibs.
