### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by ahoischen** [devkitPro/3ds_portlibs#20]
Right now you are not permitting anyone to redistribute your source or compiled binaries. I have also seen the argument that forking could be considered a trademark violation without a proper license. You are also *technically* violating your contributor's copyright ([Source](https://choosealicense.com/no-license/)). It would be nice if a `LICENSE` file was included at the root of the project to take care of that. My personal recommendation is the MIT License, but you may choose your own at [Choose a License](https://choosealicense.com/).

**Comment by WinterMute** [comment]
This repo isn't really anything more than a Makefile used to keep notes on compiling various libraries for 3DS. The libraries used here so far all have their own licenses and we don't feel the need to provide an extra  license to muddy the waters an cause confusion with those licenses.
