### ISSUE TITLE
Cannot build mbedtls-apache

### ISSUE THREAD

**Issue by PabloMK7** [devkitPro/3ds_portlibs#38]
I'm not being able to compile mbedtls-apache
Here is the terminal output: https://pastebin.com/0n4mwZ6e

Trying to compile in windows, latest devkitpro installed, cmake 3.11.0-rc3

**Comment by PabloMK7** [comment]
Trying to trace the issue, looks like DCMAKE_C_COMPILER is being ignored.

**Comment by WinterMute** [comment]
cmake is a waste of space.
