### ISSUE TITLE
Tremor doesn't want to install

### ISSUE THREAD

**Issue by cadenza-k** [devkitPro/3ds_portlibs#9]
Hello,

When I do "make tremor install" (libogg is already installed), I got an error that said it did not found a command ( PKG_PROG_PKG_CONFIG)

Logged the error : http://pastebin.com/rPNeKx9j

**Comment by WinterMute** [comment]
You need to install pkg-config

**Comment by ahoischen** [comment]
Tremor is still not compiling. On cmd it softlocks and git-bash throws `sed` pattern errors according to @MarcuzD. On a clean Linux install with all listed dependencies satisfied it reports the following:
```
configure: WARNING: unrecognized options: --disable-oggtest
<snip>
checking pkg-config is at least version 0.9.0... yes
checking for OGG... yes
./configure: line 11979: syntax error near unexpected token `,'
./configure: line 11979: `    XIPH_PATH_OGG(, as_fn_error $? "must have Ogg installed!" "$LINENO" 5)'
Makefile:297: recipe for target 'tremor' failed
```
